computeType: AKS

autoScaler:
    autoscaleEnabled: True
    minReplicas: 1
    maxReplicas: 3
    refreshPeriodInSeconds: 10
    targetUtilization: 70

containerResourceRequirements:
  cpu: 0.5
  memoryInGB: 0.25

# Only one can be True
authEnabled: True
tokenAuthEnabled: False

appInsightsEnabled: True
sslEnabled: True

dataCollection:
  storageEnabled: True