name: german-credit-train
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.7.9
- pip:
  # Azure ML
  - azureml-defaults>=1.19.0
  - azureml-sdk>=1.19.0
  - azureml-interpret
  # Other
  - scikit-learn==0.20.3
  - joblib==0.13.2
  - pandas==1.2.3