name: german-credit-train
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.7.9
- pip:
  # Azure ML
  - azureml-defaults==1.33.0
  - azureml-sdk==1.33.0
  - azureml-interpret==1.33.0
  # Other
  - scikit-learn==0.24.1
  - joblib==1.0.0
  - pandas==1.2.1
